# Generated by Django 3.1 on 2021-11-27 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='matn_mazmuni',
        ),
    ]
